export interface CropConfig {
  id: string;
  nameKey: string;
  rawName: string;
  image: any;
  modelAvailable: boolean;
  diseaseModelAvailable?: boolean;
  pestModelAvailable?: boolean;
  nutrientModelAvailable?: boolean;
  category: 'cereal' | 'pulse' | 'oilseed' | 'commercial' | 'vegetable' | 'fruit' | 'plantation' | 'spice' | 'other';
  searchKeywords: string[];
}

export const CROPS_CONFIG: CropConfig[] = [
  {
    id: 'paddy',
    nameKey: 'crop.paddy',
    rawName: 'Paddy',
    image: require('../../assets/crops/paddy.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: true,
    nutrientModelAvailable: true,
    category: 'cereal',
    searchKeywords: ["paddy", "rice", "oryza", "dhan", "chawal", "nel", "arisi", "bhatta", "akki", "vari", "vadlu", "nellu"],
  },
  {
    id: 'maize',
    nameKey: 'crop.maize',
    rawName: 'Maize',
    image: require('../../assets/crops/maize.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: true,
    nutrientModelAvailable: true,
    category: 'cereal',
    searchKeywords: ["maize", "corn", "zea mays", "makka", "bhutta", "makkacholam", "mekkejola", "musukinajola", "mokkajonna"],
  },
  {
    id: 'ragi',
    nameKey: 'crop.ragi',
    rawName: 'Ragi',
    image: require('../../assets/crops/ragi.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["ragi", "finger millet", "eleusine coracana", "kezhvaragu", "keppai", "ragulu", "mandia"],
  },
  {
    id: 'sorghum',
    nameKey: 'crop.sorghum',
    rawName: 'Sorghum',
    image: require('../../assets/crops/sorghum.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["sorghum", "jowar", "sorghum bicolor", "cholam", "jola", "bili jola", "jonna"],
  },
  {
    id: 'pearl_millet',
    nameKey: 'crop.pearlMillet',
    rawName: 'Pearl Millet',
    image: require('../../assets/crops/pearl_millet.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["pearl millet", "bajra", "pennisetum glaucum", "kambu", "sajje", "sajjalu"],
  },
  {
    id: 'foxtail_millet',
    nameKey: 'crop.foxtailMillet',
    rawName: 'Foxtail Millet',
    image: require('../../assets/crops/foxtail_millet.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["foxtail millet", "setaria italica", "navane", "tenai", "korra", "kangni", "thina"],
  },
  {
    id: 'little_millet',
    nameKey: 'crop.littleMillet',
    rawName: 'Little Millet',
    image: require('../../assets/crops/little_millet.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["little millet", "panicum sumatrense", "same", "samai", "sama", "samalu", "kutki"],
  },
  {
    id: 'kodo_millet',
    nameKey: 'crop.kodoMillet',
    rawName: 'Kodo Millet',
    image: require('../../assets/crops/kodo_millet.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["kodo millet", "paspalum scrobiculatum", "harka", "varagu", "arikelu", "kodra"],
  },
  {
    id: 'barnyard_millet',
    nameKey: 'crop.barnyardMillet',
    rawName: 'Barnyard Millet',
    image: require('../../assets/crops/barnyard_millet.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["barnyard millet", "echinochloa frumentacea", "oodalu", "kuthiraivali", "udhalu", "oodalu", "sanwa"],
  },
  {
    id: 'proso_millet',
    nameKey: 'crop.prosoMillet',
    rawName: 'Proso Millet',
    image: require('../../assets/crops/proso_millet.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["proso millet", "panicum miliaceum", "baragu", "panivaragu", "variga", "chena"],
  },
  {
    id: 'wheat',
    nameKey: 'crop.wheat',
    rawName: 'Wheat',
    image: require('../../assets/crops/wheat.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'cereal',
    searchKeywords: ["wheat", "triticum", "gehun", "godhi", "godhumai", "godhuma", "gothambu"],
  },
  {
    id: 'red_gram',
    nameKey: 'crop.redGram',
    rawName: 'Red Gram',
    image: require('../../assets/crops/red_gram.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'pulse',
    searchKeywords: ["red gram", "pigeon pea", "tur", "arhar", "cajanus cajan", "togari", "thuvaram", "kandi"],
  },
  {
    id: 'black_gram',
    nameKey: 'crop.blackGram',
    rawName: 'Black Gram',
    image: require('../../assets/crops/black_gram.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'pulse',
    searchKeywords: ["black gram", "urad", "vigna mungo", "uddu", "ulundu", "minumulu", "uzhunnu"],
  },
  {
    id: 'green_gram',
    nameKey: 'crop.greenGram',
    rawName: 'Green Gram',
    image: require('../../assets/crops/green_gram.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'pulse',
    searchKeywords: ["green gram", "moong", "vigna radiata", "hesaru", "paasi payaru", "pesalu", "cherupayar"],
  },
  {
    id: 'bengal_gram',
    nameKey: 'crop.bengalGram',
    rawName: 'Bengal Gram',
    image: require('../../assets/crops/bengal_gram.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'pulse',
    searchKeywords: ["bengal gram", "chickpea", "chana", "cicer arietinum", "kadale", "konda kadalai", "senagalu", "kadala"],
  },
  {
    id: 'cowpea',
    nameKey: 'crop.cowpea',
    rawName: 'Cowpea',
    image: require('../../assets/crops/cowpea.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'pulse',
    searchKeywords: ["cowpea", "lobia", "vigna unguiculata", "alasande", "karamani", "thatta payaru", "alasandalu", "payar"],
  },
  {
    id: 'field_bean',
    nameKey: 'crop.fieldBean',
    rawName: 'Field Bean',
    image: require('../../assets/crops/field_bean.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'pulse',
    searchKeywords: ["field bean", "hyacinth bean", "avarekalu", "lablab purpureus", "mochai", "chikkudu", "amara"],
  },
  {
    id: 'groundnut',
    nameKey: 'crop.groundnut',
    rawName: 'Groundnut',
    image: require('../../assets/crops/groundnut.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'oilseed',
    searchKeywords: ["groundnut", "peanut", "arachis hypogaea", "mungphali", "shenga", "kadalakkai", "verukadalai", "verusenaga"],
  },
  {
    id: 'sesame',
    nameKey: 'crop.sesame',
    rawName: 'Sesame',
    image: require('../../assets/crops/sesame.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'oilseed',
    searchKeywords: ["sesame", "gingelly", "til", "sesamum indicum", "ellu", "nuvvulu"],
  },
  {
    id: 'sunflower',
    nameKey: 'crop.sunflower',
    rawName: 'Sunflower',
    image: require('../../assets/crops/sunflower.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'oilseed',
    searchKeywords: ["sunflower", "helianthus annuus", "surajmukhi", "suryakanti", "sooriyaganthi", "proddutirugudu"],
  },
  {
    id: 'castor',
    nameKey: 'crop.castor',
    rawName: 'Castor',
    image: require('../../assets/crops/castor.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'oilseed',
    searchKeywords: ["castor", "ricinus communis", "arandi", "haralu", "aamanakku", "aamudamu", "aavanakku"],
  },
  {
    id: 'safflower',
    nameKey: 'crop.safflower',
    rawName: 'Safflower',
    image: require('../../assets/crops/safflower.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'oilseed',
    searchKeywords: ["safflower", "carthamus tinctorius", "kusube", "kardi", "kusum", "sendurakam", "kusumalu"],
  },
  {
    id: 'soybean',
    nameKey: 'crop.soybean',
    rawName: 'Soybean',
    image: require('../../assets/crops/soybean.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'oilseed',
    searchKeywords: ["soybean", "soya", "glycine max", "soyachikkudu", "soya bean"],
  },
  {
    id: 'cotton',
    nameKey: 'crop.cotton',
    rawName: 'Cotton',
    image: require('../../assets/crops/cotton.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: true,
    nutrientModelAvailable: true,
    category: 'commercial',
    searchKeywords: ["cotton", "kapas", "gossypium", "hatti", "paruthi", "pratti", "panji"],
  },
  {
    id: 'sugarcane',
    nameKey: 'crop.sugarcane',
    rawName: 'Sugarcane',
    image: require('../../assets/crops/sugarcane.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'commercial',
    searchKeywords: ["sugarcane", "saccharum", "ganna", "kabbu", "karumbu", "cheraku", "karimbu"],
  },
  {
    id: 'tobacco',
    nameKey: 'crop.tobacco',
    rawName: 'Tobacco',
    image: require('../../assets/crops/tobacco.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'commercial',
    searchKeywords: ["tobacco", "nicotiana", "tambaku", "hogesoppu", "pugaielai", "pogaku", "pukayila"],
  },
  {
    id: 'tomato',
    nameKey: 'crop.tomato',
    rawName: 'Tomato',
    image: require('../../assets/crops/tomato.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: true,
    nutrientModelAvailable: true,
    category: 'vegetable',
    searchKeywords: ["tomato", "tamatar", "solanum lycopersicum", "thakkali", "tometo", "tamata"],
  },
  {
    id: 'chilli',
    nameKey: 'crop.chilli',
    rawName: 'Chilli',
    image: require('../../assets/crops/chilli.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: true,
    nutrientModelAvailable: true,
    category: 'vegetable',
    searchKeywords: ["chilli", "chili", "capsicum", "mirch", "menasinakayi", "milagai", "mirapakaya", "mulaku"],
  },
  {
    id: 'brinjal',
    nameKey: 'crop.brinjal',
    rawName: 'Brinjal',
    image: require('../../assets/crops/brinjal.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["brinjal", "eggplant", "aubergine", "solanum melongena", "baingan", "badanekayi", "kathirikai", "vankaya", "vazhuthananga"],
  },
  {
    id: 'onion',
    nameKey: 'crop.onion',
    rawName: 'Onion',
    image: require('../../assets/crops/onion.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["onion", "allium cepa", "pyaz", "eerulli", "vengayam", "ullipayalu", "ulli", "savala"],
  },
  {
    id: 'okra',
    nameKey: 'crop.okra',
    rawName: 'Okra',
    image: require('../../assets/crops/okra.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["okra", "bhindi", "bhendi", "lady finger", "abelmoschus esculentus", "bende", "vendakkai", "bhendakaya"],
  },
  {
    id: 'potato',
    nameKey: 'crop.potato',
    rawName: 'Potato',
    image: require('../../assets/crops/potato.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["potato", "solanum tuberosum", "aaloo", "aloo", "alugadde", "urulaikizhangu", "bangaladumpa", "urulakizhangu"],
  },
  {
    id: 'tapioca',
    nameKey: 'crop.tapioca',
    rawName: 'Tapioca',
    image: require('../../assets/crops/tapioca.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["tapioca", "cassava", "manihot esculenta", "maravalli kizhangu", "maragenasu", "karra pendalam", "kappa"],
  },
  {
    id: 'sweet_potato',
    nameKey: 'crop.sweetPotato',
    rawName: 'Sweet Potato',
    image: require('../../assets/crops/sweet_potato.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["sweet potato", "ipomoea batatas", "shakarkand", "sihi genasu", "sakkaravalli kizhangu", "chilagada dumpa", "madhurakkizhangu"],
  },
  {
    id: 'drumstick',
    nameKey: 'crop.drumstick',
    rawName: 'Drumstick',
    image: require('../../assets/crops/drumstick.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["drumstick", "moringa", "moringa oleifera", "sehjan", "nuggekayi", "murungakkai", "mulakkada", "muringakka"],
  },
  {
    id: 'cucumber',
    nameKey: 'crop.cucumber',
    rawName: 'Cucumber',
    image: require('../../assets/crops/cucumber.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["cucumber", "cucumis sativus", "kheera", "southekayi", "vellarikkai", "dosakaya", "vellarikka"],
  },
  {
    id: 'pumpkin',
    nameKey: 'crop.pumpkin',
    rawName: 'Pumpkin',
    image: require('../../assets/crops/pumpkin.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["pumpkin", "cucurbita moschata", "kaddu", "kumbalakayi", "parangikkai", "gummadikaya", "matthan"],
  },
  {
    id: 'bitter_gourd',
    nameKey: 'crop.bitterGourd',
    rawName: 'Bitter Gourd',
    image: require('../../assets/crops/bitter_gourd.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["bitter gourd", "momordica charantia", "karela", "hagalakayi", "paavakkai", "kakarakaya", "pavakka"],
  },
  {
    id: 'bottle_gourd',
    nameKey: 'crop.bottleGourd',
    rawName: 'Bottle Gourd',
    image: require('../../assets/crops/bottle_gourd.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["bottle gourd", "lagenaria siceraria", "lauki", "sorekayi", "suraikkai", "sorakaya", "churakka"],
  },
  {
    id: 'ridge_gourd',
    nameKey: 'crop.ridgeGourd',
    rawName: 'Ridge Gourd',
    image: require('../../assets/crops/ridge_gourd.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["ridge gourd", "luffa acutangula", "turai", "hirekayi", "peerkangai", "beerakaya", "peechinga"],
  },
  {
    id: 'beans',
    nameKey: 'crop.beans',
    rawName: 'Beans',
    image: require('../../assets/crops/beans.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["beans", "french beans", "phaseolus vulgaris", "huralikayi", "beans", "chikkudukai"],
  },
  {
    id: 'cabbage',
    nameKey: 'crop.cabbage',
    rawName: 'Cabbage',
    image: require('../../assets/crops/cabbage.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["cabbage", "brassica oleracea", "patta gobhi", "kosu", "muttaikose", "cabbage", "muttakose"],
  },
  {
    id: 'cauliflower',
    nameKey: 'crop.cauliflower',
    rawName: 'Cauliflower',
    image: require('../../assets/crops/cauliflower.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["cauliflower", "brassica oleracea var botrytis", "phool gobhi", "hookosu", "kaaliflavar", "gobi"],
  },
  {
    id: 'carrot',
    nameKey: 'crop.carrot',
    rawName: 'Carrot',
    image: require('../../assets/crops/carrot.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["carrot", "daucus carota", "gajar", "gaajare", "kerat", "carrot"],
  },
  {
    id: 'beetroot',
    nameKey: 'crop.beetroot',
    rawName: 'Beetroot',
    image: require('../../assets/crops/beetroot.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'vegetable',
    searchKeywords: ["beetroot", "beta vulgaris", "chukandar", "beetroot"],
  },
  {
    id: 'banana',
    nameKey: 'crop.banana',
    rawName: 'Banana',
    image: require('../../assets/crops/banana.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["banana", "plantain", "musa", "kela", "baale", "vazhai", "arati", "vazha"],
  },
  {
    id: 'mango',
    nameKey: 'crop.mango',
    rawName: 'Mango',
    image: require('../../assets/crops/mango.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["mango", "mangifera indica", "aam", "maavu", "maanga", "maamidikaya"],
  },
  {
    id: 'papaya',
    nameKey: 'crop.papaya',
    rawName: 'Papaya',
    image: require('../../assets/crops/papaya.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["papaya", "carica papaya", "papita", "parangi", "pappali", "boppayi", "omakkaya"],
  },
  {
    id: 'pomegranate',
    nameKey: 'crop.pomegranate',
    rawName: 'Pomegranate',
    image: require('../../assets/crops/pomegranate.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["pomegranate", "punica granatum", "anaar", "dalimbe", "madhulai", "danimma", "mathalam"],
  },
  {
    id: 'guava',
    nameKey: 'crop.guava',
    rawName: 'Guava',
    image: require('../../assets/crops/guava.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["guava", "psidium guajava", "amrood", "seebe", "koyya", "jama", "pera"],
  },
  {
    id: 'sapota',
    nameKey: 'crop.sapota',
    rawName: 'Sapota',
    image: require('../../assets/crops/sapota.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["sapota", "chikoo", "manilkara zapota", "chiku", "sapota"],
  },
  {
    id: 'pineapple',
    nameKey: 'crop.pineapple',
    rawName: 'Pineapple',
    image: require('../../assets/crops/pineapple.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["pineapple", "ananas comosus", "ananas", "parangi", "annasi", "kaithachakka"],
  },
  {
    id: 'grapes',
    nameKey: 'crop.grapes',
    rawName: 'Grapes',
    image: require('../../assets/crops/grapes.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["grapes", "vitis vinifera", "angoor", "drakshi", "thiratchai", "draksha", "muntiringa"],
  },
  {
    id: 'jackfruit',
    nameKey: 'crop.jackfruit',
    rawName: 'Jackfruit',
    image: require('../../assets/crops/jackfruit.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["jackfruit", "artocarpus heterophyllus", "kathal", "halasu", "pala", "panasa", "chakka"],
  },
  {
    id: 'watermelon',
    nameKey: 'crop.watermelon',
    rawName: 'Watermelon',
    image: require('../../assets/crops/watermelon.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["watermelon", "citrullus lanatus", "tarbooz", "kallangadi", "tharpoosani", "puchakaya", "thannimathan"],
  },
  {
    id: 'muskmelon',
    nameKey: 'crop.muskmelon',
    rawName: 'Muskmelon',
    image: require('../../assets/crops/muskmelon.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["muskmelon", "cantaloupe", "cucumis melo", "kharbooja", "kirni", "kekkarikke"],
  },
  {
    id: 'citrus_lime',
    nameKey: 'crop.citrusLime',
    rawName: 'Acid Lime',
    image: require('../../assets/crops/citrus_lime.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'fruit',
    searchKeywords: ["citrus", "lime", "lemon", "citrus aurantifolia", "nimbu", "nimbe", "elumichai", "nimmakaya", "cherunaranga"],
  },
  {
    id: 'coconut',
    nameKey: 'crop.coconut',
    rawName: 'Coconut',
    image: require('../../assets/crops/coconut.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: true,
    nutrientModelAvailable: true,
    category: 'plantation',
    searchKeywords: ["coconut", "cocos nucifera", "nariyal", "tengu", "thennai", "kobbari", "thengu"],
  },
  {
    id: 'arecanut',
    nameKey: 'crop.arecanut',
    rawName: 'Arecanut',
    image: require('../../assets/crops/arecanut.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["arecanut", "betel nut", "areca catechu", "supari", "adike", "pakku", "vakka", "adakka"],
  },
  {
    id: 'cashew',
    nameKey: 'crop.cashew',
    rawName: 'Cashew',
    image: require('../../assets/crops/cashew.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["cashew", "anacardium occidentale", "kaju", "geru", "munthiri", "jeedipappu", "kasu"],
  },
  {
    id: 'coffee',
    nameKey: 'crop.coffee',
    rawName: 'Coffee',
    image: require('../../assets/crops/coffee.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["coffee", "coffea arabica", "coffea canephora", "kaapi", "coffee"],
  },
  {
    id: 'tea',
    nameKey: 'crop.tea',
    rawName: 'Tea',
    image: require('../../assets/crops/tea.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["tea", "camellia sinensis", "chai", "theila", "chaha"],
  },
  {
    id: 'rubber',
    nameKey: 'crop.rubber',
    rawName: 'Rubber',
    image: require('../../assets/crops/rubber.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["rubber", "hevea brasiliensis", "rubber", "latex"],
  },
  {
    id: 'cocoa',
    nameKey: 'crop.cocoa',
    rawName: 'Cocoa',
    image: require('../../assets/crops/cocoa.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["cocoa", "theobroma cacao", "cacao", "cocoa"],
  },
  {
    id: 'oil_palm',
    nameKey: 'crop.oilPalm',
    rawName: 'Oil Palm',
    image: require('../../assets/crops/oil_palm.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["oil palm", "elaeis guineensis", "palm oil", "thalamaram"],
  },
  {
    id: 'palmyrah',
    nameKey: 'crop.palmyrah',
    rawName: 'Palmyrah',
    image: require('../../assets/crops/palmyrah.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'plantation',
    searchKeywords: ["palmyrah", "borassus flabellifer", "tale", "panai", "thati", "pana"],
  },
  {
    id: 'black_pepper',
    nameKey: 'crop.blackPepper',
    rawName: 'Black Pepper',
    image: require('../../assets/crops/black_pepper.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["black pepper", "piper nigrum", "kalimirch", "menasu", "karumilagu", "miriyalu", "kurumulaku"],
  },
  {
    id: 'cardamom',
    nameKey: 'crop.cardamom',
    rawName: 'Cardamom',
    image: require('../../assets/crops/cardamom.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["cardamom", "elettaria cardamomum", "elaichi", "yelakki", "elakkai", "elakulu", "elakka"],
  },
  {
    id: 'turmeric',
    nameKey: 'crop.turmeric',
    rawName: 'Turmeric',
    image: require('../../assets/crops/turmeric.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["turmeric", "curcuma longa", "haldi", "arishina", "manjal", "pasupu", "manjal"],
  },
  {
    id: 'ginger',
    nameKey: 'crop.ginger',
    rawName: 'Ginger',
    image: require('../../assets/crops/ginger.png'),
    modelAvailable: true,
    diseaseModelAvailable: true,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["ginger", "zingiber officinale", "adrak", "shunti", "inji", "allam", "inji"],
  },
  {
    id: 'clove',
    nameKey: 'crop.clove',
    rawName: 'Clove',
    image: require('../../assets/crops/clove.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["clove", "syzygium aromaticum", "laung", "lavanga", "krambu", "lavangalu", "karambu"],
  },
  {
    id: 'coriander',
    nameKey: 'crop.coriander',
    rawName: 'Coriander',
    image: require('../../assets/crops/coriander.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["coriander", "coriandrum sativum", "dhaniya", "kothambari", "kothamalli", "dhaniyalu", "malli"],
  },
  {
    id: 'cumin',
    nameKey: 'crop.cumin',
    rawName: 'Cumin',
    image: require('../../assets/crops/cumin.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["cumin", "cuminum cyminum", "jeera", "jeerige", "seeragam", "jeelakarra", "jeerakam"],
  },
  {
    id: 'fenugreek',
    nameKey: 'crop.fenugreek',
    rawName: 'Fenugreek',
    image: require('../../assets/crops/fenugreek.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'spice',
    searchKeywords: ["fenugreek", "trigonella foenum-graecum", "methi", "menthya", "vendhayam", "menthulu", "uluva"],
  },
  {
    id: 'betel_vine',
    nameKey: 'crop.betelVine',
    rawName: 'Betel Vine',
    image: require('../../assets/crops/betel_vine.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'other',
    searchKeywords: ["betel vine", "piper betle", "paan", "veelyada yele", "vetrilai", "tamalapaaku", "vettila"],
  },
  {
    id: 'tamarind',
    nameKey: 'crop.tamarind',
    rawName: 'Tamarind',
    image: require('../../assets/crops/tamarind.png'),
    modelAvailable: false,
    diseaseModelAvailable: false,
    pestModelAvailable: false,
    nutrientModelAvailable: false,
    category: 'other',
    searchKeywords: ["tamarind", "tamarindus indica", "imli", "hunase", "puli", "chintha", "vaalanpuli"],
  },
];

export const getCropById = (id: string): CropConfig | undefined => {
  const norm = id.toLowerCase().trim();
  return CROPS_CONFIG.find((c) => c.id === norm || c.rawName.toLowerCase() === norm);
};
